name: der_mpc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.24.3
  - scipy
  - matplotlib=3.7.1
  - pyyaml
  - cmake
  - pip
  - pip:
      - casadi
      - acados-template
      - -e .
